void Send62 (PSO_CLIENT* client);
void Send08 (PSO_CLIENT* client);
void Send1A (const char *mes, PSO_CLIENT* client);
void Send1A (const char *mes, PSO_CLIENT* client);
void Send83 (PSO_CLIENT* client);
void Send64 (PSO_CLIENT* client);
void Send67 (PSO_CLIENT* client, unsigned char preferred);
void Send95 (PSO_CLIENT* client);
void SendA2 (unsigned char episode, unsigned char solo, unsigned char category, unsigned char gov, PSO_CLIENT* client);
void SendA0 (PSO_CLIENT* client);
void Send07 (PSO_CLIENT* client);
void SendB0 (const char *mes, PSO_CLIENT* client);
void SendEE (const char *mes, PSO_CLIENT* client);
void Send19 (unsigned char ip1, unsigned char ip2, unsigned char ip3, unsigned char ip4, unsigned short ipp, PSO_CLIENT* client);
void SendEA (unsigned char command, PSO_CLIENT* client);
unsigned char* MakePacketEA15 (PSO_CLIENT* client);
void ShipSend04 (unsigned char command, PSO_CLIENT* client, PSO_SERVER* ship);
void ShipSend0E (PSO_SERVER* ship);
void ShipSend0D (unsigned char command, PSO_CLIENT* client, PSO_SERVER* ship);
void ShipSend0B (PSO_CLIENT* client, PSO_SERVER* ship);
void LogonProcessPacket (PSO_SERVER* ship);
void Send60 (PSO_CLIENT* client);
void Send6D (PSO_CLIENT* client);
void Send01 (const char *text, PSO_CLIENT* client);
void Send06 (PSO_CLIENT* client);
